[package]
name = "sd-clock-hw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quanta = "0.10"
approx = "0.5"
rand = "0.8"

[dev-dependencies]
rstest = "0.17"
